# Spring Boot configuration for tests.

spring:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test;Mode=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    continue-on-error: true

